services:
  postgres_db:
    image: postgres:16-alpine
    container_name: sports_ticket_postgres
    restart: always
    environment:
      POSTGRES_DB: sports_ticket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: persianlord@0171
    ports:
      - "5433:5432"
    volumes:
      - ./database/scripts:/scripts
      - ./database/init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sports_ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: sports_ticket_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ./backend
    container_name: sports_ticket_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(2); s.connect(('127.0.0.1', 8000)); s.close()",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  celery_worker:
    build:
      context: ./backend
    container_name: sports_ticket_celery
    command: celery -A app.tasks.reservation_tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
    driver: local
